package c.m.pwdo2.area_stp_requirement.presentation.state

data class AreaStpRequirementUIState(
    val isLogin: Boolean = false,
    val isLoading: Boolean = false,
    val isError: Boolean = false,
    val isSuccess: Boolean = false,
    val isRefresh: Boolean = false,
    val isExpanded: Boolean = false,
    val isExpandedCardA: Boolean = false,
    val isExpandedCardB: Boolean = false,
    val isExpandedCardC: Boolean = false,
    val isExpandedCardD: Boolean = false,
    val isExpandedCardE: Boolean = false,
    val isExpandedCardF: Boolean = false,
    val isExpandedCardG: Boolean = false,
    val isLoadingCardA: Boolean = false,
    val isLoadingCardB: Boolean = false,
    val isLoadingCardC: Boolean = false,
    val isLoadingCardD: Boolean = false,
    val isLoadingCardE: Boolean = false,
    val isLoadingCardF: Boolean = false,
    val isLoadingCardG: Boolean = false,
    // Input Parameters data
    val inputBodInlet: Double = 0.0,
    val inputCodInlet: Double = 0.0,
    val inputNhThreeInlet: Double = 0.0,
    val inputFlowRate: Double = 0.0,
    val inputPeakHourAssumption: Double = 0.0,
    val inputWaterDepthAboveDiffuser: Double = 0.0,
    // Standard Value
    val retentionTimeAnaerob: Double = 0.0,
    val percentBwTowardsTotalFlowForHotel: Double = 0.0,
    val percentBwTowardsTotalFlowForIndustry: Double = 0.0,
    val targetBodReductionFromAnaerob: Double = 0.0,
    val retentionTimeAeration: Double = 0.0,
    val targetBodReductionFromAeration: Double = 0.0,
    val targetCodReductionFromAeration: Double = 0.0,
    val targetNhThreeReductionFromAeration: Double = 0.0,
    val retentionTimeGreaseTrap: Double = 0.0,
    val totalChamberGreaseTrap: Double = 0.0,
    val targetFogRemovalFromGreaseTrap: Double = 0.0,
    val retentionTimeSedimentation: Double = 0.0,
    val targetTssRemovalFromGreaseTrap: Double = 0.0,
    val retentionTimeChlorination: Double = 0.0,
    val targetEcoliRemovalFromChlorination: Double = 0.0,
    // Anaerob Room
    val volumeAnaerobRoom: Double = 0.0,
    val lengthAnaerobRoom: String = "",
    val widthAnaerobRoom: Double = 0.0,
    val depthAnaerobRoom: Double = 0.0,
    // Grease Trap Room
    val volumeGreaseTrapRoom: Double = 0.0,
    val lengthGreaseTrapRoom: String = "",
    val widthGreaseTrapRoom: Double = 0.0,
    val depthGreaseTrapRoom: String = "",
    // Aerob Room
    val volumeAerobRoom: Double = 0.0,
    val lengthAerobRoom: String = "",
    val widthAerobRoom: Double = 0.0,
    val depthAerobRoom: Double = 0.0,
    // Aeration chamber volume with diffuser twelve inch
    val aerationChamberVolumeWithDiffuserTwelveInch: Double = 0.0,
    // Sedimentation Room
    val volumeSedimentationRoom: Double = 0.0,
    val lengthSedimentationRoom: String = "",
    val widthSedimentationRoom: Double = 0.0,
    val depthSedimentationRoom: Double = 0.0,
    // Chlorination Room
    val volumeChlorinationRoom: Double = 0.0,
    val lengthChlorinationRoom: String = "",
    val widthChlorinationRoom: Double = 0.0,
    val depthChlorinationRoom: String = "",
    // Filtration Tank
    val volumeFiltrationTankRoom: Double = 0.0,
    val lengthFiltrationTankRoom: String = "",
    val widthFiltrationTankRoom: Double = 0.0,
    val depthFiltrationTankRoom: Double = 0.0,
    // Recycle Tank
    val volumeRecycleTankRoom: String = "",
    val lengthRecycleTankRoom: String = "",
    val widthRecycleTankRoom: Double = 0.0,
    val depthRecycleTankRoom: Double = 0.0,
)