package c.m.pwdo2.oxygen_requirement_and_area.presentation.state

data class OxygenRequirementAndAreaUIState(
    val isLoading: Boolean = false,
    val isError: Boolean = false,
    val isSuccess: Boolean = false,
    val isRefresh: Boolean = false,
    val isExpandedInputParametersCard: Boolean = false,
    val isExpandedAllCard: Boolean = false,
    val isLogin: Boolean = false,
    // Input Parameters data
    val isLoadingInputParametersCard: Boolean = false,
    val inputBodInlet: String = "",
    val inputBodOutlet: String = "",
    val inputCodInlet: String = "",
    val inputCodOutlet: String = "",
    val inputNhThreeInlet: String = "",
    val inputNhThreeOutlet: String = "",
    val inputFlowRate: String = "",
    val inputPeakHourAssumption: String = "",
    val inputWaterDepthAboveDiffuser: String = "",
    // Standard Value
    val oneKgBodStandard: Double = 0.0,
    val oneKgCodStandard: Double = 0.0,
    val oneKgNhThreeStandard: Double = 0.0,
    val percentOxygenInAirStandard: Double = 0.0,
    val densityOfOxygenStandard: Double = 0.0,
    val diffuserCapacityTwelveInchStandard: Double = 0.0,
    val diffuserCapacityNineInchStandard: Double = 0.0,
    val percentOxygenTransferEfficiencyStandard: Double = 0.0,
    val effectiveSurfaceAreaDiffTwelveInchStandard: Double = 0.0,
    val effectiveSurfaceAreaDiffNineInchStandard: Double = 0.0,
    val minimumMixingAreaStandard: Double = 0.0,
    val targetBodReductionFromAnaerob: Double = 0.0,
    val targetBodReductionFromAeration: Double = 0.0,
    val targetCodReductionFromAeration: Double = 0.0,
    val targetNhThreeReductionFromAeration: Double = 0.0,
    // Diffuser Depth Efficiency
    val diffuserDepthEfficiency: Double = 0.0,
    // Total Influent Loading Per Hour
    val totalBodInlet: Double = 0.0,
    val totalCodInlet: Double = 0.0,
    val totalNhThreeInlet: Double = 0.0,
    // Air Requirement
    val forBodPerMinute: Double = 0.0,
    val forCodPerMinute: Double = 0.0,
    val forNhThreePerMinute: Double = 0.0,
    val totalAirRequirementPerMinute: Double = 0.0,
    val forBodPerHour: Double = 0.0,
    val forCodPerHour: Double = 0.0,
    val forNhThreePerHour: Double = 0.0,
    val totalAirRequirementPerHour: Double = 0.0,
    // Diffuser Requirement,
    val diffuserTwelveUnit: Double = 0.0,
    val diffuserTwelveUnitRoundUp: Double = 0.0,
    val diffuserNineUnit: Double = 0.0,
    val diffuserNineUnitRoundUp: Double = 0.0,
    // Blower Capacity Requirement
    val blowerCapacityRequirementPerMinute: Double = 0.0,
    val blowerCapacityRequirementPerHour: Double = 0.0,
    // Area Volume Requirement
    val aerationChamberAreaWithDiffuserTwelveInch: Double = 0.0,
    val aerationChamberVolumeWithDiffuserTwelveInch: Double = 0.0,
)
