package c.m.pwdo2.oxygen_requirement_and_area.domain.model

data class StandardValue(
    val oneKgBodStandard: Double = 0.0,
    val oneKgCodStandard: Double = 0.0,
    val oneKgNhThreeStandard: Double = 0.0,
    val percentOxygenInAirStandard: Double = 0.0,
    val densityOfOxygenStandard: Double = 0.0,
    val diffuserCapacityTwelveInchStandard: Double = 0.0,
    val diffuserCapacityNineInchStandard: Double = 0.0,
    val percentOxygenTransferEfficiencyStandard: Double = 0.0,
    val effectiveSurfaceAreaDiffTwelveInchStandard: Double = 0.0,
    val effectiveSurfaceAreaDiffNineInchStandard: Double = 0.0,
    val minimumMixingAreaStandard: Double = 0.0,
    val retentionTimeAnaerob: Double = 0.0,
    val percentBwTowardsTotalFlowForHotel: Double = 0.0,
    val percentBwTowardsTotalFlowForIndustry: Double = 0.0,
    val targetBodReductionFromAnaerob: Double = 0.0,
    val retentionTimeAeration: Double = 0.0,
    val targetBodReductionFromAeration: Double = 0.0,
    val targetCodReductionFromAeration: Double = 0.0,
    val targetNhThreeReductionFromAeration: Double = 0.0,
    val retentionTimeGreaseTrap: Double = 0.0,
    val totalChamberGreaseTrap: Double = 0.0,
    val targetFogRemovalFromGreaseTrap: Double = 0.0,
    val retentionTimeSedimentation: Double = 0.0,
    val targetTssRemovalFromGreaseTrap: Double = 0.0,
    val retentionTimeChlorination: Double = 0.0,
    val targetEcoliRemovalFromChlorination: Double = 0.0,
)
